import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
require('dotenv').config();

import 'primereact/resources/themes/lara-light-indigo/theme.css'; // Thème PrimeReact
import 'primereact/resources/primereact.min.css'; // CSS des composants PrimeReact
import 'primeicons/primeicons.css'; // Icônes PrimeReact
import 'primeflex/primeflex.css'; // PrimeFlex pour la disposition

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
